# Generated by Django 5.2 on 2025-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodechefDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('solved', models.BinaryField()),
            ],
        ),
    ]
