# Generated by Django 5.2 on 2025-05-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_codechefdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodechefDB',
        ),
    ]
