# Generated by Django 5.2 on 2025-07-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_codechefdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='current_streak',
            new_name='ultimate_streak',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='codechef_streak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='codeforces_streak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_streak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
