# Generated by Django 5.2 on 2025-06-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solutionurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
