# Generated by Django 5.2 on 2025-06-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_problem_solutionurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potdstatus',
            name='assigned_date',
        ),
        migrations.AddField(
            model_name='problem',
            name='assigned_date',
            field=models.DateField(null=True),
        ),
    ]
