# Generated by Django 5.2 on 2025-07-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_remove_potdstatus_assigned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potdstatus',
            name='solved_date',
            field=models.DateField(null=True),
        ),
    ]
