# Generated by Django 5.2 on 2025-07-18 10:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_potdstatus_solved_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='potdstatus',
            unique_together={('user', 'solved_date')},
        ),
    ]
